/**
 * minih inspect <slug> — show the fully composed prompt an agent receives.
 *
 * Mirrors the exact assembly logic from runner.ts but adds section markers
 * and runtime injection details. Pure read-only — no SDK, no execution.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import chalk from 'chalk';
import type { Command } from 'commander';
import {
  listAgents,
  parseFrontmatter,
  resolveAgent,
  SYSTEM_OUTPUT_INSTRUCTIONS,
  validateSlug,
} from '../../runner/index.js';
import {
  ErrorCodes,
  exitWithEnvelope,
  formatError,
  formatSuccess,
} from '../output.js';
import { parseParamFlags } from '../param-parser.js';

interface PromptSection {
  label: string;
  source: string;
  content: string;
}

export function registerInspectCommand(program: Command): void {
  program
    .command('inspect <slug>')
    .description('Show the fully composed prompt an agent receives')
    .option('--resolved', 'Show with runtime variables resolved (default)')
    .option('--raw', 'Show without resolving template variables')
    .option(
      '-p, --param <key=value>',
      'Input parameter (repeatable)',
      (val: string, acc: string[]) => {
        acc.push(val);
        return acc;
      },
      [] as string[],
    )
    .action(
      (
        slug: string,
        opts: { resolved?: boolean; raw?: boolean; param?: string[] },
      ) => {
        const agentsDir = program.opts().agentsDir ?? 'agents';
        const resolve = !opts.raw;

        const slugError = validateSlug(slug);
        if (slugError) {
          exitWithEnvelope(
            formatError('inspect', ErrorCodes.INVALID_ARGS, slugError),
          );
        }

        const definition = resolveAgent(slug, agentsDir);
        if (!definition) {
          const available = listAgents(agentsDir).map((a) => a.slug);
          exitWithEnvelope(
            formatError(
              'inspect',
              ErrorCodes.AGENT_NOT_FOUND,
              `Agent "${slug}" not found.${available.length ? ` Available: ${available.join(', ')}` : ''}`,
            ),
          );
          return;
        }

        const repoRoot = process.cwd();
        const sections: PromptSection[] = [];

        // 1. Shared preamble
        const preamblePath = path.join(
          path.resolve(agentsDir),
          '_shared',
          'preamble.md',
        );
        if (fs.existsSync(preamblePath)) {
          let content = fs.readFileSync(preamblePath, 'utf-8');
          if (resolve) {
            content = content.replaceAll('{{REPO_ROOT}}', repoRoot);
          }
          sections.push({
            label: 'PREAMBLE',
            source: path.relative(repoRoot, preamblePath),
            content,
          });
        }

        // 2. Instructions (optional)
        if (
          definition.instructionsPath &&
          fs.existsSync(definition.instructionsPath)
        ) {
          sections.push({
            label: 'INSTRUCTIONS',
            source: path.relative(repoRoot, definition.instructionsPath),
            content: fs.readFileSync(definition.instructionsPath, 'utf-8'),
          });
        }

        // 3. Output hint
        const outputPath = resolve
          ? `<run-dir>/output/report.json`
          : '$MINIH_OUTPUT_PATH';
        sections.push({
          label: 'OUTPUT HINT',
          source: '(auto-generated by minih)',
          content: `Write your final JSON report to: ${outputPath}`,
        });

        // 4. Input params (auto-coerces JSON values per FX001).
        const { params } = parseParamFlags(opts.param ?? []);
        // inspect intentionally tolerates malformed entries (skips them silently)
        // since this is a read-only preview command — keep that behavior.
        if (Object.keys(params).length > 0) {
          const lines = Object.entries(params).map(
            ([k, v]) =>
              `${k}: ${typeof v === 'string' ? v : (JSON.stringify(v) ?? String(v))}`,
          );
          sections.push({
            label: 'INPUT PARAMS',
            source: '--param flags',
            content: `## Input Parameters\n\n${lines.join('\n')}`,
          });
        }

        // 5. Agent prompt (frontmatter stripped)
        const rawPrompt = fs.readFileSync(definition.promptPath, 'utf-8');
        const {
          body: promptBody,
          description,
          tags,
          model,
          reasoning,
          timeout,
        } = parseFrontmatter(rawPrompt);
        sections.push({
          label: 'PROMPT',
          source: path.relative(repoRoot, definition.promptPath),
          content: promptBody,
        });

        // 6. System output requirements
        sections.push({
          label: 'SYSTEM REQUIREMENTS',
          source: '(auto-generated by minih)',
          content: SYSTEM_OUTPUT_INSTRUCTIONS,
        });

        // Compose exactly as runner does
        const composed = sections.map((s) => s.content).join('\n\n---\n\n');

        // Runtime env vars the agent would see
        const envVars: Record<string, string> = {
          MINIH: '1',
          MINIH_AGENT_SLUG: slug,
          MINIH_RUN_ID: '<generated-at-runtime>',
          MINIH_RUN_DIR: '<generated-at-runtime>',
          MINIH_OUTPUT_PATH: '<run-dir>/output/report.json',
          MINIH_AGENTS_DIR: path.resolve(agentsDir),
          MINIH_PROJECT_ROOT: repoRoot,
          MINIH_MODEL:
            model ?? process.env.MINIH_DEFAULT_MODEL ?? 'claude-opus-4.6',
          MINIH_TIMEOUT: String(timeout ?? 900),
          MINIH_SCHEMA_PATH: definition.schemaPath ?? '',
          MINIH_INSTRUCTIONS_PATH: definition.instructionsPath ?? '',
          MINIH_PREAMBLE_PATH: fs.existsSync(preamblePath) ? preamblePath : '',
          MINIH_HAS_INPUT_SCHEMA: definition.inputSchemaPath ? 'true' : 'false',
        };

        // MCP config discovery
        const mcpJsonPath = path.join(repoRoot, '.mcp.json');
        const hasMcpConfig = fs.existsSync(mcpJsonPath);
        const mcpConfigSource = hasMcpConfig
          ? `auto-discovery (${mcpJsonPath})`
          : 'none';

        // TTY display with section markers
        if (process.stderr.isTTY) {
          process.stderr.write(
            `\n${chalk.bold(`─── Inspect: ${slug} ───`)}\n\n`,
          );

          // Frontmatter summary
          if (description || tags.length || model || reasoning || timeout) {
            process.stderr.write(chalk.bold('  Frontmatter:\n'));
            if (description)
              process.stderr.write(
                `    description: ${chalk.dim(description)}\n`,
              );
            if (tags.length)
              process.stderr.write(`    tags: ${chalk.dim(tags.join(', '))}\n`);
            if (model) process.stderr.write(`    model: ${chalk.dim(model)}\n`);
            if (reasoning)
              process.stderr.write(`    reasoning: ${chalk.dim(reasoning)}\n`);
            if (timeout)
              process.stderr.write(
                `    timeout: ${chalk.dim(String(timeout))}s\n`,
              );
            process.stderr.write('\n');
          }

          for (const section of sections) {
            process.stderr.write(
              `${chalk.cyan(`--- ${section.label}`)} ${chalk.dim(`(${section.source}, ${section.content.length} chars)`)} ${chalk.cyan('---')}\n`,
            );
            process.stderr.write(`${section.content}\n\n`);
          }

          process.stderr.write(chalk.bold('─── Runtime Environment ───\n'));
          for (const [key, val] of Object.entries(envVars)) {
            process.stderr.write(`  ${chalk.dim(key)}=${val}\n`);
          }
          process.stderr.write(
            `  ${chalk.dim('MCP config')}=${mcpConfigSource}\n`,
          );

          process.stderr.write(`\n${chalk.bold('─── Stats ───')}\n`);
          process.stderr.write(`  Sections:     ${sections.length}\n`);
          process.stderr.write(
            `  Total chars:  ${composed.length.toLocaleString()}\n`,
          );
          process.stderr.write(
            `  Est. tokens:  ~${Math.round(composed.length / 4).toLocaleString()}\n\n`,
          );
        }

        // Stdout: full composed prompt for piping
        process.stdout.write(composed);

        exitWithEnvelope(
          formatSuccess('inspect', {
            slug,
            sections: sections.map((s) => ({
              label: s.label,
              source: s.source,
              chars: s.content.length,
            })),
            totalChars: composed.length,
            estimatedTokens: Math.round(composed.length / 4),
            frontmatter: { description, tags, model, reasoning, timeout },
            envVars,
            mcpConfig: mcpConfigSource,
          }),
        );
      },
    );
}
